import express from 'express';
import {registerClub , getAllClubs, getClubById, updateClub , deleteClub} from '../controllers/clubController';
import { protect } from '../middlewares/authMiddleware';
import { isClubOwner } from '../middlewares/clubMiddleware';
const router = express.Router();
router.route('/register').post(protect,registerClub);
router.route('/all').get(getAllClubs);
router.route('/:id').get(getClubById);
router.route('/update').put(protect,isClubOwner, updateClub);
router.route('/delete/:id').delete(protect,isClubOwner, deleteClub);
export default router;