import express from 'express';
import {createEvent,getAllEvents,getEventById,updateEvent,deleteEvent} from '../controllers/eventController';
import { protect } from '../middlewares/authMiddleware';
import { isEventOrganiser } from '../middlewares/eventMiddleware';
import { isClubOwner } from '../middlewares/clubMiddleware';
const router = express.Router();
router.route('/register').post(protect,isClubOwner,createEvent);
router.route('/all').get(getAllEvents);
router.route('/:id').get(getEventById);
router.route('/update/:id').put(protect,isEventOrganiser, updateEvent);
router.route('/delete/:id').delete(protect,isEventOrganiser, deleteEvent);
export default router;
